### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by helgeolav** [udhos/acigo#2]
Hi

I have just started to look into acigo and it works good for me. Some features that I need are missing (like toggling VRF enforced mode) and I see two ways to solve it:

1. Make a fork and add the code from there.
2. Make my changes into this repository from a branch.

What do you think is the right approach?

**Comment by udhos** [comment]
Hi,
I am not really sure, but I think that github kind of encourages contribution thru forking plus pull requests.

**Comment by helgeolav** [comment]
Hi

Thanks for the reply. I am a bit new to making changes to Github. I have created a fork, done some modifications and created a pull request. If this is a good way do it I will continue and change some more code.

**Comment by udhos** [comment]
Merged, thanks.
